CREATE TABLE employee ( 
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL UNIQUE,
    tel VARCHAR(15) NOT NULL,
    sector VARCHAR(200) NOT NULL
);

