CREATE TABLE cars ( 
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT DEFAULT NULL,
    car_img VARCHAR(500) NOT NULL,
    model VARCHAR(100) NOT NULL,
    brand VARCHAR(100) NOT NULL,
    status ENUM('Disponível', 'Reservado', 'Alugado') DEFAULT 'Disponível',
    category_id INT NOT NULL,
    description VARCHAR(400) NOT NULL, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES categories(id),
    FOREIGN KEY (user_id) REFERENCES users(id) 
);

INSERT INTO cars (car_img, model, brand, status, category_id, description, created_at)
VALUES
    ('https://i0.statig.com.br/bancodeimagens/5i/yu/tz/5iyutzxo0075uln4pbhjlepjw.jpg', 'Chevrolet Onix', 'Chevrolet', 'Disponível', 2, 'O Chevrolet Onix é um dos modelos mais populares do Brasil, conhecido por sua economia de combustível e design moderno. Compacto e prático, é ideal para quem busca um carro versátil para o dia a dia, com bom desempenho nas cidades e conforto para viagens curtas. Seu interior é bem equipado, com tecnologia atual, como a conectividade com smartphones e sistemas de segurança, como o controle de estabilidade.', NOW()),
    ('https://upload.wikimedia.org/wikipedia/commons/e/e3/Volkswagen_Gol_Highline_2023_%2853708009248%29_%28cropped%29.jpg', 'Volkswagen Gol', 'Volkswagen', 'Disponível', 2, 'O Volkswagen Gol é um dos carros mais icônicos do mercado brasileiro, com mais de 40 anos de história. Seu design simples e robusto o torna uma excelente escolha para quem busca um carro confiável e de baixo custo de manutenção. O Gol é conhecido por sua durabilidade e por ser um carro fácil de dirigir, com bom consumo de combustível e excelente custo-benefício, perfeito tanto para iniciantes quanto para quem precisa de um veículo econômico para o dia a dia.', NOW()),
    ('https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Ford_Fiesta_ST-Line_%28VII%2C_Facelift%29_%E2%80%93_f_30012023.jpg/800px-Ford_Fiesta_ST-Line_%28VII%2C_Facelift%29_%E2%80%93_f_30012023.jpg', 'Ford Fiesta', 'Ford', 'Disponível', 1, 'O Ford Fiesta é um hatch compacto que combina design esportivo e desempenho ágil, oferecendo uma experiência de direção divertida e dinâmica. Com um interior bem acabado, o Fiesta é equipado com tecnologias modernas de conectividade e segurança, como câmeras de ré e sistemas de assistência ao motorista. Seu tamanho compacto o torna ideal para o trânsito urbano, enquanto o motor eficiente garante uma condução agradável e com baixo consumo de combustível.', NOW()),

    ('https://cdn.oantagonista.com/uploads/2024/09/dfac5492-18f7-40dc-9c63-495c68eccf92-1024x683.jpeg', 'Toyota Corolla', 'Toyota', 'Disponível', 3, 'O Toyota Corolla é um dos sedãs mais populares e confiáveis do mundo. Com um design moderno, confortável e de fácil manutenção, é uma excelente opção para quem busca um carro versátil para o dia a dia. Seu desempenho equilibrado, baixo consumo de combustível e uma cabine bem equipada fazem dele uma escolha inteligente para quem busca conforto e eficiência.', NOW()),
    ('https://autoranking.com.br/wp-content/uploads/2024/05/WhatsApp-Image-2024-05-06-at-14.45.02-2.jpeg', 'Honda Civic', 'Honda', 'Disponível', 3, 'O Honda Civic é um dos modelos mais icônicos da Honda, conhecido por seu design esportivo e desempenho confiável. Oferece um interior confortável, com tecnologia avançada e excelente economia de combustível. O Civic é perfeito para quem busca um carro com um bom equilíbrio entre performance, conforto e custo-benefício.', NOW()),
    ('https://blog.karvi.com.br/wp-content/uploads/2024/03/novo-ford-mustang-gt-2024-brasil.jpg', 'Ford Mustang', 'Ford', 'Disponível', 1, 'O Ford Mustang é um dos carros esportivos mais famosos do mundo, oferecendo potência, design agressivo e uma experiência de direção única. Disponível com motores V8 e V6, o Mustang combina desempenho excepcional com tecnologia de ponta e um interior de alto nível, sendo uma opção para quem busca adrenalina e sofisticação.', NOW()),
    ('https://revistacarro.com.br/wp-content/uploads/2022/05/BMW-3-Series-Sedan_3.jpg', 'BMW Série 3', 'BMW', 'Disponível', 1, 'O BMW Série 3 é um sedã de luxo que combina desempenho esportivo com conforto e elegância. Equipado com motores potentes e uma suspensão refinada, o Série 3 oferece uma experiência de condução superior. Seu interior é sofisticado, com materiais premium e tecnologia de ponta, tornando-o ideal para quem procura performance e conforto.', NOW()),
    ('https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/2020_Volkswagen_Golf_Style_TDi_S-A_2.0.jpg/1200px-2020_Volkswagen_Golf_Style_TDi_S-A_2.0.jpg', 'Volkswagen Golf', 'Volkswagen', 'Disponível', 3, 'O Volkswagen Golf é um hatchback versátil e prático, conhecido pela sua confiabilidade e boa performance. Com um design moderno e acabamento de qualidade, o Golf oferece uma experiência de direção agradável, excelente consumo de combustível e uma cabine bem equipada, sendo uma excelente escolha para quem busca um carro equilibrado e de fácil manutenção.', NOW()),
    ('https://www.automaistv.com.br/wp-content/uploads/2019/05/chevrolet_camaro_lt1.jpg', 'Chevrolet Camaro', 'Chevrolet', 'Disponível', 1, 'O Chevrolet Camaro é um muscle car com design imponente e desempenho de tirar o fôlego. Equipado com potentes motores V8 e um visual agressivo, o Camaro oferece uma experiência de direção emocionante. Além disso, seu interior combina conforto e tecnologia avançada, tornando-o uma excelente escolha para quem deseja um carro esportivo de luxo com muita potência.', NOW());
